[pytest]
testpaths = connectors
pythonpath = connectors/jira connectors/jira/tests connectors/zendesk connectors/zendesk/tests connectors/_shared connectors/_shared/tests connectors
addopts = --import-mode=importlib
